package dotty:hellowasm;

world helloworld {
  // Imports: exercises @WitImport, @WitRecord, @WitVariant, @WitFlags,
  // @WitResourceImport, @WitResourceMethod, @WitResourceDrop, etc.
  import wasi:random/random@0.2.0;
  import wasi:clocks/wall-clock@0.2.0;
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:io/error@0.2.0;
  import wasi:io/poll@0.2.0;
  import wasi:io/streams@0.2.0;
  import wasi:cli/stdout@0.2.0;
  import wasi:http/types@0.2.0;
  import wasi:http/outgoing-handler@0.2.0;

  export wasi:cli/run@0.2.0;
}
